-- MySQL Script generated by MySQL Workbench
-- Sat Mar 16 10:28:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `api` ;

-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api` DEFAULT CHARACTER SET utf8mb4 ;
USE `api` ;

-- -----------------------------------------------------
-- Table `api`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`users` ;

CREATE TABLE IF NOT EXISTS `api`.`users` (
  `user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `api`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`groups` ;

CREATE TABLE IF NOT EXISTS `api`.`groups` (
  `group_id` INT(10) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `isGuest` VARCHAR(4) NOT NULL DEFAULT '0',
  `isUser` VARCHAR(4) NOT NULL DEFAULT '0',
  `isAdmin` VARCHAR(4) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`group_id`),
  INDEX `fk_username_idx` (`username` ASC),
  CONSTRAINT `fk_username`
    FOREIGN KEY (`username`)
    REFERENCES `api`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `api`.`passwords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`passwords` ;

CREATE TABLE IF NOT EXISTS `api`.`passwords` (
  `password_id` INT(11) NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(60) NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`password_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `username`
    FOREIGN KEY (`username`)
    REFERENCES `api`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
